# Generated by Django 4.2.5 on 2025-05-07 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_initial_products'),
    ]

    operations = [
    ]
