# Generated by Django 4.2.5 on 2025-05-07 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0056_initial_products'),
    ]

    operations = [
    ]
