# Generated by Django 4.2.5 on 2025-05-08 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0059_initial_products'),
    ]

    operations = [
    ]
