# Generated by Django 4.2.5 on 2025-05-08 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0065_initial_products'),
    ]

    operations = [
    ]
