# Generated by Django 4.2.5 on 2025-05-08 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0068_initial_products'),
    ]

    operations = [
    ]
