# Generated by Django 4.2.5 on 2025-06-19 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0077_initial_products'),
    ]

    operations = [
    ]
