# Generated by Django 4.2.5 on 2025-05-07 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
    ]
