# Generated by Django 4.2.5 on 2025-05-07 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_initial_accounts'),
    ]

    operations = [
    ]
