# Generated by Django 4.2.5 on 2025-05-07 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_initial_accounts'),
    ]

    operations = [
    ]
