# Generated by Django 4.2.5 on 2025-05-08 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_initial_accounts'),
    ]

    operations = [
    ]
