# Generated by Django 4.2.5 on 2025-05-08 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_initial_accounts'),
    ]

    operations = [
    ]
