# Generated by Django 4.2.5 on 2025-06-19 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0072_initial_accounts'),
    ]

    operations = [
    ]
