# Generated by Django 4.2.5 on 2025-06-19 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0076_initial_accounts'),
    ]

    operations = [
    ]
