upstream django {
    server web:8000;
}

upstream websocket {
    server daphne:8000;
}

server {
    listen 80;
    server_name sduclubs.asia www.sduclubs.asia;

    # Перенаправление всех запросов с HTTP на HTTPS
    location / {
        return 301 https://$host$request_uri;
    }

    # Нужно оставить для автоматического обновления сертификатов
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
}

server {
    listen 443 ssl;
    server_name sduclubs.asia www.sduclubs.asia;

    # Пути к сертификатам внутри контейнера (они проброшены через volume)
    ssl_certificate /etc/letsencrypt/live/sduclubs.asia/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sduclubs.asia/privkey.pem;

    client_max_body_size 100M;

    location /static/ {
        alias /app/static/;
    }

    location /media/ {
        alias /app/media/;
    }

    # WebSocket (WSS)
    location ~ ^/ws/ {
        proxy_pass http://websocket;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $server_name;
        proxy_set_header X-Forwarded-Proto https;
    }

    # Django App
    location / {
        proxy_pass http://django;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}