# Generated by Django 4.2.5 on 2025-05-07 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_activities', '0026_initial_user_activity'),
    ]

    operations = [
    ]
