# Generated by Django 4.2.5 on 2025-05-07 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_activities', '0029_initial_user_activity'),
    ]

    operations = [
    ]
