# Generated by Django 4.2.5 on 2025-05-07 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_activities', '0035_initial_user_activity'),
    ]

    operations = [
    ]
