# Generated by Django 4.2.5 on 2025-05-07 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_activities', '0042_initial_user_activity'),
    ]

    operations = [
    ]
