# Generated by Django 4.2.5 on 2025-05-08 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_activities', '0063_initial_user_activity'),
    ]

    operations = [
    ]
