# Generated by Django 4.2.5 on 2025-05-08 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_activities', '0067_initial_user_activity'),
    ]

    operations = [
    ]
