# Generated by Django 4.2.5 on 2025-06-19 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_activities', '0069_initial_user_activity'),
    ]

    operations = [
    ]
